package com.github.jozott00.wokwiintellij.testing

import com.github.jozott00.wokwiintellij.testing.fixtures.Fixtures
import com.github.jozott00.wokwiintellij.testing.harness.runWokwiTest
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test

/** Exercises the complete HEX path: configuration, binary loading, JCEF bridge, firmware execution and Run console. */
@Tag("live-wokwi")
class HexFirmwareTest {
    /** A print generated by AVR firmware proves that HEX text reached the simulator and UART reached the IDE. */
    @Test fun hexFirmwareExecutesAndPrintsToTheRunConsole() = runWokwiTest(Fixtures.avrUart) {
        simulator.start()
        console.awaitText("AVR simulation ready\n")
        simulator.stopAndAwaitTermination()
    }
}
